### ISSUE TITLE
Fix Deathmessages plox

### ISSUE THREAD

**Issue by michuthecomrade** [EmotionalLove/ReMinecraft#10]
[RE:Minecraft 1.1.5 / INFO] (CHAT) {"extra":[{"extra":[{"extra":[{"color":"white","text":""}],"text":""},{"color":"dark_aqua","text":"IHackedCSGO"},{"color":"dark_red","text":" pummeled "},{"color":"dark_aqua","text":"TGB_Skeletor"},{"color":"dark_red","text":" to death using "},{"color":"gold","text":""},{"color":"gold","extra":[{"color":"gold","text":"Shuhadaku"}],"hoverEvent":{"action":"show_item","value":[{"text":"{id:\"minecraft:diamond_sword\",Count:1b,tag:{ench:[{lvl:5s,id:16s},{lvl:2s,id:19s},{lvl:2s,id:20s},{lvl:3s,id:21s},{lvl:3s,id:22s},{lvl:3s,id:34s},{lvl:1s,id:70s}],RepairCost:63,display:{Name:\"Shuhadaku\"}},Damage:53s}"}]},"text":""}],"text":""}],"text":""}

**Comment by EmotionalLove** [comment]
Try using release 1.1.6 and tell me if it's fixed

**Comment by michuthecomrade** [comment]
not fixed yet boss
