### ISSUE TITLE
Updates in the API

### ISSUE THREAD

**Issue by robertt** [EmotionalLove/ReMinecraft#26]
Maybe I'm just being retarded but is there an event/way to detect when a client gets disconnected from the proxy? If not could you please add one?

**Comment by EmotionalLove** [comment]
ur right there isn't one smh
ill add one

**Comment by robertt** [comment]
cheers

**Comment by Haxified** [comment]
@EmotionalLove now pls

**Comment by Mhowser** [comment]
Geez impatient much?

**Comment by EvilSourcerer** [comment]
@haxified do it yourself if you want it fast

**Comment by EmotionalLove** [comment]
done
