### ISSUE TITLE
Use Dependency Management System

### ISSUE THREAD

**Issue by ZeroMemes** [EmotionalLove/ReMinecraft#3]
Please for the love of god use Gradle for dependency management

**Comment by ZeroMemes** [comment]
Or maven it literally doesn't matter just do sOMETHING

**Comment by EmotionalLove** [comment]
it would be more helpful if u like made pr's for this instead of issues :roll_eyes:

**Comment by ZeroMemes** [comment]
mf u use gradle in Adorufu figure it out

**Comment by EmotionalLove** [comment]
k its done
